/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.2.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

import java.io.File
import java.nio.file.Files
import java.nio.file.Path

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "buildlogic-gradle"

val rootPath = rootDir.toPath()
val excludedRoots = setOf(rootPath.resolve("buildSrc")).filter { Files.exists(it) }

fun Path.hasBuildScript(): Boolean =
    Files.isRegularFile(resolve("build.gradle.kts")) || Files.isRegularFile(resolve("build.gradle"))

fun Path.hasNoBuildMarker(): Boolean = Files.isRegularFile(resolve(".nobuild"))

fun Path.toGradleProjectPath(root: Path): String {
    val relative = root.relativize(this).toString().replace(File.separatorChar, ':')
    return ":$relative"
}

Files.walk(rootPath).use { paths ->
    paths
        .filter { Files.isDirectory(it) }
        .filter { it != rootPath } 
        .filter { candidate -> excludedRoots.none { candidate.startsWith(it) } }
        .filter { candidate -> candidate.hasBuildScript() && !candidate.hasNoBuildMarker() }
        .map { it.toGradleProjectPath(rootPath) }
        .sorted()
        .forEach { include(it) }
}

